/* The following code was generated by JFlex 1.6.1 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>exemploSem.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\62\1\3\1\63\1\63\1\4\22\0\1\62\1\0\1\61"+
    "\1\0\1\5\1\0\1\26\1\0\1\21\1\21\1\21\1\21\1\21"+
    "\1\21\1\2\1\21\12\1\1\22\1\21\1\25\1\23\1\24\2\0"+
    "\1\10\1\60\1\11\1\60\1\12\1\16\2\60\1\56\2\60\1\54"+
    "\1\17\1\15\1\14\2\60\1\7\1\20\1\6\2\60\1\53\3\60"+
    "\1\21\1\0\1\21\1\0\1\13\1\0\1\47\1\37\1\46\1\42"+
    "\1\31\1\51\1\44\1\52\1\36\1\60\1\55\1\41\1\50\1\34"+
    "\1\40\1\57\1\60\1\30\1\43\1\32\1\33\1\45\1\35\3\60"+
    "\1\21\1\27\1\21\7\0\1\63\u1fa2\0\1\63\1\63\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\1\2\5\2\3"+
    "\2\1\17\5\1\1\1\6\3\0\1\5\1\7\1\10"+
    "\1\11\1\12\7\5\1\13\14\5\1\0\1\14\1\15"+
    "\2\0\5\5\1\16\1\5\1\17\7\5\1\20\4\5"+
    "\2\0\5\5\1\21\1\22\2\5\1\23\3\5\1\24"+
    "\1\5\1\25\1\5\1\26\2\5\2\0\4\5\1\27"+
    "\1\30\1\31\3\5\1\32\1\33\2\5\2\0\1\5"+
    "\1\34\1\35\1\5\1\36\1\37\1\40\2\5\2\0"+
    "\1\41\2\5\1\42\2\0\1\43\1\44\1\45\2\0"+
    "\1\46\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\64\0\234\0\320\0\u0104"+
    "\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4"+
    "\0\u0618\0\u064c\0\64\0\64\0\64\0\64\0\u0680\0\u06b4"+
    "\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u0104\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\u0548\0\64\0\u05b0\0\u0a5c\0\u0a90\0\u0ac4"+
    "\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0104\0\u0bc8\0\u0104\0\u0bfc"+
    "\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0104\0\u0d68"+
    "\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08"+
    "\0\u0f3c\0\u0f70\0\u0104\0\u0104\0\u0fa4\0\u0fd8\0\u0104\0\u100c"+
    "\0\u1040\0\u1074\0\u0104\0\u10a8\0\u0104\0\u10dc\0\u0104\0\u1110"+
    "\0\u1144\0\u1178\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c\0\u0104"+
    "\0\u0104\0\u0104\0\u12b0\0\u12e4\0\u1318\0\u0104\0\u0104\0\u134c"+
    "\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u0104\0\u0104\0\u1450\0\u0104"+
    "\0\u0104\0\u0104\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u0104\0\u1554"+
    "\0\u1588\0\64\0\u15bc\0\u15f0\0\u0104\0\64\0\64\0\u1624"+
    "\0\u1658\0\64\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\4\10\1\11"+
    "\1\2\5\10\2\4\1\12\1\13\1\4\1\14\1\15"+
    "\1\16\1\17\1\20\1\10\1\21\1\22\1\23\1\24"+
    "\2\10\1\25\1\26\1\10\1\27\1\30\1\10\1\31"+
    "\1\32\2\10\1\33\2\10\1\34\1\10\1\35\1\36"+
    "\66\0\1\3\1\37\64\0\1\5\66\0\1\40\10\0"+
    "\1\41\45\0\1\10\4\0\13\10\7\0\31\10\4\0"+
    "\1\10\4\0\13\10\7\0\13\10\1\42\15\10\30\0"+
    "\1\43\61\0\1\44\66\0\1\45\64\0\1\46\35\0"+
    "\1\10\4\0\13\10\7\0\1\10\1\47\27\10\4\0"+
    "\1\10\4\0\13\10\7\0\4\10\1\50\4\10\1\51"+
    "\17\10\4\0\1\10\4\0\13\10\7\0\1\52\30\10"+
    "\4\0\1\10\4\0\13\10\7\0\1\10\1\53\27\10"+
    "\4\0\1\10\4\0\13\10\7\0\22\10\1\54\6\10"+
    "\4\0\1\10\4\0\13\10\7\0\4\10\1\55\14\10"+
    "\1\56\7\10\4\0\1\10\4\0\13\10\7\0\1\57"+
    "\7\10\1\60\20\10\4\0\1\10\4\0\13\10\7\0"+
    "\10\10\1\61\20\10\4\0\1\10\4\0\13\10\7\0"+
    "\2\10\1\62\26\10\4\0\1\10\4\0\13\10\7\0"+
    "\10\10\1\63\20\10\4\0\1\10\4\0\13\10\7\0"+
    "\11\10\1\64\17\10\4\0\1\10\4\0\13\10\7\0"+
    "\17\10\1\65\11\10\4\0\1\10\4\0\13\10\7\0"+
    "\10\10\1\66\6\10\1\67\11\10\4\0\1\10\4\0"+
    "\13\10\7\0\1\10\1\70\27\10\4\0\1\10\4\0"+
    "\13\10\7\0\1\71\2\10\1\72\25\10\3\0\61\73"+
    "\1\74\2\73\62\0\1\36\2\0\1\75\71\0\1\76"+
    "\70\0\1\77\50\0\1\10\4\0\13\10\7\0\16\10"+
    "\1\100\12\10\4\0\1\10\4\0\13\10\7\0\2\10"+
    "\1\101\26\10\4\0\1\10\4\0\13\10\7\0\12\10"+
    "\1\102\16\10\4\0\1\10\4\0\13\10\7\0\13\10"+
    "\1\103\15\10\4\0\1\10\4\0\13\10\7\0\3\10"+
    "\1\104\25\10\4\0\1\10\4\0\13\10\7\0\5\10"+
    "\1\105\23\10\4\0\1\10\4\0\13\10\7\0\6\10"+
    "\1\106\22\10\4\0\1\10\4\0\13\10\7\0\2\10"+
    "\1\107\26\10\4\0\1\10\4\0\13\10\7\0\1\10"+
    "\1\110\27\10\4\0\1\10\4\0\13\10\7\0\10\10"+
    "\1\111\20\10\4\0\1\10\4\0\13\10\7\0\3\10"+
    "\1\112\25\10\4\0\1\10\4\0\13\10\7\0\1\113"+
    "\30\10\4\0\1\10\4\0\13\10\7\0\6\10\1\114"+
    "\22\10\4\0\1\10\4\0\13\10\7\0\17\10\1\115"+
    "\11\10\4\0\1\10\4\0\13\10\7\0\6\10\1\116"+
    "\22\10\4\0\1\10\4\0\13\10\7\0\1\117\30\10"+
    "\4\0\1\10\4\0\13\10\7\0\11\10\1\120\17\10"+
    "\4\0\1\10\4\0\13\10\7\0\6\10\1\121\22\10"+
    "\4\0\1\10\4\0\13\10\7\0\6\10\1\122\22\10"+
    "\4\0\1\10\4\0\13\10\7\0\7\10\1\123\21\10"+
    "\13\0\1\124\73\0\1\125\44\0\1\10\4\0\13\10"+
    "\7\0\1\126\30\10\4\0\1\10\4\0\13\10\7\0"+
    "\3\10\1\127\25\10\4\0\1\10\4\0\10\10\1\130"+
    "\2\10\7\0\23\10\1\131\2\10\1\132\2\10\4\0"+
    "\1\10\4\0\13\10\7\0\1\10\1\133\27\10\4\0"+
    "\1\10\4\0\13\10\7\0\1\10\1\134\27\10\4\0"+
    "\1\10\4\0\13\10\7\0\11\10\1\135\17\10\4\0"+
    "\1\10\4\0\13\10\7\0\17\10\1\136\11\10\4\0"+
    "\1\10\4\0\13\10\7\0\11\10\1\137\17\10\4\0"+
    "\1\10\4\0\13\10\7\0\7\10\1\140\21\10\4\0"+
    "\1\10\4\0\13\10\7\0\3\10\1\141\2\10\1\142"+
    "\22\10\4\0\1\10\4\0\13\10\7\0\12\10\1\143"+
    "\16\10\4\0\1\10\4\0\13\10\7\0\13\10\1\144"+
    "\15\10\4\0\1\10\4\0\13\10\7\0\4\10\1\145"+
    "\24\10\4\0\1\10\4\0\13\10\7\0\13\10\1\146"+
    "\15\10\4\0\1\10\4\0\13\10\7\0\17\10\1\147"+
    "\11\10\4\0\1\10\4\0\13\10\7\0\15\10\1\150"+
    "\13\10\4\0\1\10\4\0\13\10\7\0\11\10\1\151"+
    "\17\10\14\0\1\152\60\0\1\153\56\0\1\10\4\0"+
    "\13\10\7\0\1\10\1\154\27\10\4\0\1\10\4\0"+
    "\13\10\7\0\1\155\30\10\4\0\1\10\4\0\13\10"+
    "\7\0\10\10\1\156\20\10\4\0\1\10\4\0\13\10"+
    "\7\0\22\10\1\157\6\10\4\0\1\10\4\0\13\10"+
    "\7\0\21\10\1\160\7\10\4\0\1\10\4\0\13\10"+
    "\7\0\1\10\1\161\27\10\4\0\1\10\4\0\13\10"+
    "\7\0\25\10\1\162\3\10\4\0\1\10\4\0\13\10"+
    "\7\0\11\10\1\163\17\10\4\0\1\10\4\0\13\10"+
    "\7\0\16\10\1\164\12\10\4\0\1\10\4\0\13\10"+
    "\7\0\4\10\1\165\24\10\4\0\1\10\4\0\13\10"+
    "\7\0\13\10\1\166\15\10\4\0\1\10\4\0\13\10"+
    "\7\0\1\10\1\167\27\10\4\0\1\10\4\0\13\10"+
    "\7\0\17\10\1\170\11\10\4\0\1\10\4\0\13\10"+
    "\7\0\6\10\1\171\22\10\15\0\1\172\60\0\1\173"+
    "\55\0\1\10\4\0\13\10\7\0\15\10\1\174\13\10"+
    "\4\0\1\10\4\0\13\10\7\0\4\10\1\175\24\10"+
    "\4\0\1\10\4\0\13\10\7\0\1\176\30\10\4\0"+
    "\1\10\4\0\13\10\7\0\6\10\1\177\22\10\4\0"+
    "\1\10\4\0\13\10\7\0\1\10\1\200\27\10\4\0"+
    "\1\10\4\0\13\10\7\0\2\10\1\201\26\10\4\0"+
    "\1\10\4\0\13\10\7\0\14\10\1\202\14\10\4\0"+
    "\1\10\4\0\13\10\7\0\2\10\1\203\26\10\4\0"+
    "\1\10\4\0\13\10\7\0\16\10\1\204\12\10\16\0"+
    "\1\205\60\0\1\206\54\0\1\10\4\0\13\10\7\0"+
    "\17\10\1\207\11\10\4\0\1\10\4\0\13\10\7\0"+
    "\11\10\1\210\17\10\4\0\1\10\4\0\13\10\7\0"+
    "\1\10\1\211\27\10\4\0\1\10\4\0\13\10\1\0"+
    "\1\212\5\0\31\10\17\0\1\213\62\0\1\214\51\0"+
    "\1\10\4\0\13\10\7\0\1\10\1\215\27\10\4\0"+
    "\1\10\4\0\13\10\1\0\1\216\5\0\31\10\20\0"+
    "\1\217\1\220\53\0\1\221\73\0\1\222\65\0\1\223"+
    "\43\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5772];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\31\1\3\0\1\1\4\11"+
    "\24\1\1\0\1\11\1\1\2\0\24\1\2\0\24\1"+
    "\2\0\16\1\2\0\11\1\2\0\3\1\1\11\2\0"+
    "\1\1\2\11\2\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
    yyline = 1;
  }


  public int getLine() {
      return yyline;
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Error: unexpected character '"+yytext()+"' na linha "+yyline); return YYEOF;
            }
          case 40: break;
          case 2: 
            { yyparser.yylval = new ParserVal(Integer.parseInt(yytext()));
         return Parser.NUM;
            }
          case 41: break;
          case 3: 
            { return (int) yycharat(0);
            }
          case 42: break;
          case 4: 
            { yyline++;
            }
          case 43: break;
          case 5: 
            { yyparser.yylval = new ParserVal(yytext());
                     return Parser.IDENT;
            }
          case 44: break;
          case 6: 
            { 
            }
          case 45: break;
          case 7: 
            { return Parser.LESSEREQUAL;
            }
          case 46: break;
          case 8: 
            { return Parser.GREATEREQUAL;
            }
          case 47: break;
          case 9: 
            { return Parser.AND;
            }
          case 48: break;
          case 10: 
            { return Parser.OR;
            }
          case 49: break;
          case 11: 
            { return Parser.IF;
            }
          case 50: break;
          case 12: 
            { yyparser.yylval = new ParserVal(yytext());
             return Parser.LITERAL;
            }
          case 51: break;
          case 13: 
            { yyparser.yylval = new ParserVal(Float.parseFloat(yytext()));
                  return Parser.DOUBLE;
            }
          case 52: break;
          case 14: 
            { return Parser.NEW;
            }
          case 53: break;
          case 15: 
            { return Parser.INT;
            }
          case 54: break;
          case 16: 
            { return Parser.FOR;
            }
          case 55: break;
          case 17: 
            { return Parser.ELSE;
            }
          case 56: break;
          case 18: 
            { return Parser.TRUE;
            }
          case 57: break;
          case 19: 
            { return Parser.BOOL;
            }
          case 58: break;
          case 20: 
            { return Parser.VOID;
            }
          case 59: break;
          case 21: 
            { return Parser.MAIN;
            }
          case 60: break;
          case 22: 
            { return Parser.LEIA;
            }
          case 61: break;
          case 23: 
            { return Parser.ENDIF;
            }
          case 62: break;
          case 24: 
            { return Parser.WHILE;
            }
          case 63: break;
          case 25: 
            { return Parser.BREAK;
            }
          case 64: break;
          case 26: 
            { return Parser.CLASSE;
            }
          case 65: break;
          case 27: 
            { return Parser.FALSE;
            }
          case 66: break;
          case 28: 
            { return Parser.RETORNO;
            }
          case 67: break;
          case 29: 
            { return Parser.ENDFOR;
            }
          case 68: break;
          case 30: 
            { return Parser.DOUBLE;
            }
          case 69: break;
          case 31: 
            { return Parser.STRUCT;
            }
          case 70: break;
          case 32: 
            { return Parser.STRING;
            }
          case 71: break;
          case 33: 
            { return Parser.ESCREVA;
            }
          case 72: break;
          case 34: 
            { return Parser.PUBLIC;
            }
          case 73: break;
          case 35: 
            { return Parser.ENDWHILE;
            }
          case 74: break;
          case 36: 
            { return Parser.PRIVATE;
            }
          case 75: break;
          case 37: 
            { yyparser.setDebug(true);
            }
          case 76: break;
          case 38: 
            { yyparser.setDebug(false);
            }
          case 77: break;
          case 39: 
            { yyparser.listarTS();
            }
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
